### ISSUE TITLE
Edge browser extension not working anymore

### ISSUE THREAD

**Issue by urielejh** [duckduckgo/duckduckgo-privacy-extension#2647]
## Description

It's been a week or so (at least) that the extension doesn't work anymore. The icon is greyed, the popup menu is blank, and accessing the settings won't let you change anything.

Firefox's version (latest beta) works.

## Steps to Reproduce

1. step 1 Look at the icon
2. step 2 Click on it
3. Access settings

**Expected behavior:**

Colored icon, popup menu displaying something, allows to change settings

**Actual behavior:**

Grey icon, popup menu is blank, doesn't allow to change settings
**Versions**

- Extension: 2024-07-24
- Browser:  Microsoft Edge Beta 128.0.2739.22
- OS:  Windows 11 24H2 26100.1301

**Comment by kzar** [comment]
Thanks for the bug report @urielejh, we'll look into it. Out of interest, did you install the extension from the Chrome Web Store (CWS)?

**Comment by urielejh** [comment]
From the Edge one. But I also tried with the Chrome version and it's the same

**Comment by kzar** [comment]
@urielejh I've tried to reproduce the issue, but not had any luck yet. Here's what I did so far:
1. Installed DuckDuckGo extension from the Edge extension store.
2. Re-enabled the extension when Edge disabled it, then pinned the icon.
3. Navigated to https://bristolpost.co.uk and confirmed trackers were blocked, DDG icon wasn't greyed out.
4. Clicked to allowlist the page using the extension's "popup" UI (that opens when you click the DDG icon.
5. Confirmed the page reloaded and trackers were allowed.
6. Opened the extension's settings and confirmed the allowlisting entry showed up there too and could be removed.

(I tried both with the 127 stable and 128 beta versions of Edge.)

Questions:
1. Are there any steps to reproduce that I'm missing?
2. Can you reproduce the issue in the stable build of Edge too?
3. Do you have any other extensions enabled? If so, does disabling those help?

**Comment by urielejh** [comment]
1. just install the extension
2. the stable build seems unaffected
3. ublock origins and privacy badger. disabling them doesn't affect it.

**Comment by kzar** [comment]
If you're able, could you inspect the DuckDuckGo extension's "background" context and have a look for errors logged in the console? They might give us a clue what's happening here. I'm still having trouble reproducing the issue.

Some of the buttons to inspect extensions seem to have been removed in Edge, but I think if you click on the DDG icon, then right click on the popup UI and click "Inspect" that would be one way to do it.

Note: Some messages there might reveal your browsing history, so just be careful what you share here obvious as it's a public forum.

**Comment by urielejh** [comment]
i'm looking into it but... what should i be looking for?

**Comment by kzar** [comment]
I'm not sure exactly, but if you switch to the Console panel of the developer tools and then click "Default levels" you can try hiding the non-error messages. There is often some noise there, so you might see some unrelated errors, but perhaps something will come up that gives us a clue with the issue you're hitting. No worries if you can't see anything obvious, just thought it might be worth a try!

**Comment by urielejh** [comment]
826Error in event handler: Error: tried to detect trackers before rules were loaded
    at _Trackers.getTrackerData (<URL>)
    at blockHandleResponse (<URL>)
    at handleRequest (<URL>)
186Error in event handler: Error: tried to detect trackers before rules were loaded
    at _Trackers.findTracker (<URL>)
    at Object.isTracker (<URL>)
    at dropTracking3pCookiesFromRequest2 (<URL>)
55Error in event handler: Error: tried to detect trackers before rules were loaded
    at _Trackers.findTracker (<URL>)
    at Object.isTracker (<URL>)
    at dropTracking3pCookiesFromResponse2 (<URL>)

**Comment by kzar** [comment]
Yep, that one is noise unfortunately! But it shows you're looking in the right place. Might be worth closing the developer tools, trying to use the extension somehow, e.g. opening a new tab or using the settings page or whatever, then opening the developer tools again to see if a new error showed up.

But no worries if you don't have time. Thanks for the help, I will keep an eye on this to see if we can reproduce the problem.

**Comment by urielejh** [comment]
Error in event handler: Error: tried to detect trackers before rules were loaded
    at _Trackers.findTracker (chrome-extension://caoacbimdbbljakfhgikoodekdnlcgpk/public/js/background.js:5348:19)
    at Object.isTracker (chrome-extension://caoacbimdbbljakfhgikoodekdnlcgpk/public/js/background.js:24263:46)
    at dropTracking3pCookiesFromResponse2 (chrome-extension://caoacbimdbbljakfhgikoodekdnlcgpk/public/js/background.js:25234:50)

**Comment by kzar** [comment]
Yep, more noise unfortunately. Thinking about it, another thing to check might be to switch to the "Network" panel instead and look for failed requests. Those ones should be highlighted red.

**Comment by urielejh** [comment]
any news yet?
