### ISSUE TITLE
extension returns the same email

### ISSUE THREAD

**Issue by harrhp** [duckduckgo/duckduckgo-privacy-extension#2698]
## Description
After some time when i click generate private duck address extension keeps returning the same email

## Steps to Reproduce
i don't know how to reproduce it. it show up after some time

**Expected behavior:**
extension generates new email when requested

**Actual behavior:**
extension generates the same email

**Versions**

- Extension: 2024.7.24
- Browser: Vivaldi
- OS: Windows

## Additional Information
in dev tools i see request to `https://quack.duckduckgo.com/api/email/addresses` fails with `net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED`
<details>
<summary>failed http request HAR file</summary>

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "_initiator": {
          "type": "script",
          "stack": {
            "callFrames": [
              {
                "functionName": "fetchAlias",
                "scriptId": "6",
                "url": "chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js",
                "lineNumber": 30342,
                "columnNumber": 13
              }
            ],
            "parent": {
              "description": "await",
              "callFrames": [
                {
                  "functionName": "refreshAlias",
                  "scriptId": "6",
                  "url": "chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js",
                  "lineNumber": 30375,
                  "columnNumber": 17
                },
                {
                  "functionName": "",
                  "scriptId": "6",
                  "url": "chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js",
                  "lineNumber": 25562,
                  "columnNumber": 74
                },
                {
                  "functionName": "onMessage",
                  "scriptId": "6",
                  "url": "chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js",
                  "lineNumber": 904,
                  "columnNumber": 27
                }
              ]
            }
          }
        },
        "_priority": "High",
        "_resourceType": "fetch",
        "cache": {},
        "request": {
          "method": "POST",
          "url": "https://quack.duckduckgo.com/api/email/addresses",
          "httpVersion": "",
          "headers": [
            {
              "name": "Referer",
              "value": ""
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Authorization",
              "value": "Bearer 123"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED"
        },
        "serverIPAddress": "",
        "startedDateTime": "2024-08-15T18:15:44.523Z",
        "time": 147.106000003987,
        "timings": {
          "blocked": 147.106000003987,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      }
    ]
  }
}
```

</details>

<details>
<summary>errors reported by extension</summary>

```
Error in event handler: Error: tried to detect trackers before rules were loaded at _Trackers.getTrackerData (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:5263:19) at blockHandleResponse (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:17708:31) at handleRequest (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:17676:30)
```

```
Error in event handler: Error: tried to detect trackers before rules were loaded at _Trackers.findTracker (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:5348:19) at Object.isTracker (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:24263:46) at dropTracking3pCookiesFromResponse2 (chrome-extension://bkdgflcldnnnapblkhphbgpggdiikppg/public/js/background.js:25234:50)
```

```
Uncaught (in promise) Error: Duplicate script ID '1-script-injection-isolated-world'
```

```
Uncaught (in promise) TypeError: Failed to fetch
```

</details>

if i open `https://quack.duckduckgo.com/api/email/addresses` in tab manually then extension starts generating new emails again

**Comment by wangel** [comment]
I am getting the same problem.

Also, when I go to the above addresses, I get an "invalid token" page.
